### ISSUE TITLE
Facing an error Converting  infix To Postfix

### ISSUE THREAD

**Issue by Najeeb-Patoana** [Najeeb-Patoana/Stack-Queue#2]
Cant Convert infix To Postfix

**Comment by Ajax-Codeing** [comment]
char* infixToPostfix(char* infix) {
			Stack_linkedlist stack;
			int i = 0, j = 0;
			int len = strlen(infix);
			char* postfix = new char[len + 1];

			while (infix[i] != '\0') {
				if (isOperand(infix[i])) {
					postfix[j++] = infix[i++];
				} else {
					if (pre(infix[i]) > pre(stack.peek())) {
						stack.push(infix[i++]);
					} else {
						postfix[j++] = stack.pop();
					}
				}
			}

			while (!stack.isEmpty()) {
				postfix[j++] = stack.pop();
			}

			postfix[j] = '\0';
			return postfix;
		}
		Hope This will Works

**Comment by Ajax-Codeing** [comment]
> Cant Convert infix To Postfix

char* infixToPostfix(char* infix) {
			Stack_linkedlist stack;
			int i = 0, j = 0;
			int len = strlen(infix);
			char* postfix = new char[len + 1];

			while (infix[i] != '\0') {
				if (isOperand(infix[i])) {
					postfix[j++] = infix[i++];
				} else {
					if (pre(infix[i]) > pre(stack.peek())) {
						stack.push(infix[i++]);
					} else {
						postfix[j++] = stack.pop();
					}
				}
			}

			while (!stack.isEmpty()) {
				postfix[j++] = stack.pop();
			}

			postfix[j] = '\0';
			return postfix;
		}
